// client/src/utils/MediaComponent.tsx
import React, { useState, useEffect } from "react"
import cx from "classnames"
import { MediaComponentHelper } from "./MediaComponentHelper"
import { App } from "../App"

export function MediaComponent() {
    const [version, setVersion] = useState(0)
    const [helper, _] = useState(() => {
        const x = new MediaComponentHelper(App.current)
        ;(async () => {
            await x.ngOnInit()
        })()
        return x
    })
    useEffect(() => {
        helper.onChanged = () => {
            console.log("forceUpdate")
            console.log({ version })
            setVersion(version + 1)
        }
    }, [version, setVersion, helper])
    let {
        selectedMovie,
        movies,
        getName,
        goBack,
        filter,
        onFiltersChanged,
        scheduleApplyFilter,
        movie_click,
        markAsWatched,
        app,
        addConfigFolder,
        scan,
        reAnalyze,
        pageSize,
        filteredMovies,
        allMovies,
        prevPage,
        nextPage,
        tmdbV4Login,
        tmdbV4Tests,
        getAllMediaFiles,
        skip,
        tvAiringToday,
        tvOnTheAir,
        scanStatus,
        canPlay,
        play,
    } = helper

    return (
        <>
            {selectedMovie != null && (
                <div>
                    <div
                        className="selectedMovie"
                        style={{
                            background:
                                "transparent url(" + selectedMovie.tmdb?.backdrop?.original + ") top center no-repeat",
                            backgroundSize: "cover",
                        }}
                    >
                        <div className="background-cover">
                            <button className="backBtn" onClick={e => goBack()}>
                                Back
                            </button>
                            <div className="cover">
                                <img src="{selectedMovie.tmdb?.poster?.w342}" />
                            </div>
                            <div className="detailsLarge">
                                <h3 className="title">{getName(selectedMovie)}</h3>
                                <div className="tag">{selectedMovie.tmdb?.tagline}</div>
                                <div className="metadata">
                                    <span className="rate">
                                        <object type="image/svg+xml" data="../img/media/rate-icon.svg"></object>
                                        {selectedMovie.tmdb?.vote_average}
                                    </span>
                                    <span>{selectedMovie.tmdb?.release_date}</span>
                                    <span>{selectedMovie.tmdb?.runtime} minutes</span>
                                    <span>{selectedMovie.tmdb?.genres?.[0]?.name}</span>
                                </div>
                                <p className="synopsis">{selectedMovie.tmdb?.overview}</p>
                            </div>
                        </div>
                    </div>
                </div>
            )}
            {selectedMovie != null && (
                <div className="media">
                    <div className="leftpane">
                        <header className="header">
                            <a className="logo">
                                <img src="../img/media/logo.svg" />
                            </a>
                        </header>
                        <div className="filter local" onClick={e => onFiltersChanged()}>
                            <span className="title">Watchlist</span>
                            <button
                                className={cx("allmedia", filter.type == null && "selected")}
                                onClick={e => (filter.type = null)}
                            >
                                All Media
                            </button>
                            <button
                                className={cx("tv", filter.type == "tv" && "selected")}
                                onClick={e => (filter.type = "tv")}
                            >
                                TV Shows
                            </button>
                            <button
                                className={cx("movie", filter.type == "movie" && "selected")}
                                onClick={e => (filter.type = "movie")}
                            >
                                Movies
                            </button>
                            <hr />
                            <button
                                className={cx(filter.watched == null && "selected")}
                                onClick={e => (filter.watched = null)}
                            >
                                Both
                            </button>
                            <button
                                className={cx(filter.watched == true && "selected")}
                                onClick={e => (filter.watched = true)}
                            >
                                Watched
                            </button>
                            <button
                                className={cx(filter.watched == false && "selected")}
                                onClick={e => (filter.watched = false)}
                            >
                                Not Watched
                            </button>
                            <hr />
                            <button
                                className={cx(filter.groupSimilar == true && "selected")}
                                onClick={e => (filter.groupSimilar = true)}
                            >
                                Group
                            </button>
                            <button
                                className={cx(filter.groupSimilar == false && "selected")}
                                onClick={e => (filter.groupSimilar = false)}
                            >
                                Ungroup
                            </button>
                            <hr />
                            <button
                                className={cx(filter.sortBy == "fsEntry.mtime desc" && "selected")}
                                onClick={e => (filter.sortBy = "fsEntry.mtime desc")}
                            >
                                Sort1
                            </button>
                            <button
                                className={cx(filter.sortBy == "fsEntry.mtime asc" && "selected")}
                                onClick={e => (filter.sortBy = "fsEntry.mtime asc")}
                            >
                                Sort2
                            </button>
                            <button
                                className={cx(filter.sortBy == "md.episodeKey desc" && "selected")}
                                onClick={e => (filter.sortBy = "md.episodeKey desc")}
                            >
                                Sort3
                            </button>
                            <button
                                className={cx(filter.sortBy == "md.episodeKey asc" && "selected")}
                                onClick={e => (filter.sortBy = "md.episodeKey asc")}
                            >
                                Sort4
                            </button>
                        </div>
                        <div className="filter explore">
                            <span className="title">Explore</span>
                            <button className="allmedia">Most Popular</button>
                            <button className="tv">Your Feed</button>
                            <button className="movie">Recommended</button>
                        </div>
                    </div>
                    <div className="rightpane">
                        <div className="gridtop">
                            <div className="search">
                                <input
                                    type="text"
                                    placeholder="Quick Search"
                                    value="filter.search"
                                    onInput={e => scheduleApplyFilter()}
                                />
                            </div>
                        </div>
                        <ul className="pool">
                            {movies?.map(movie => (
                                <li className={cx("media", movie.tmdb?.poster?.w342 && "selected")}>
                                    <div className="poster">
                                        {movie.tmdb?.poster?.w342 && <img src={movie.tmdb?.poster?.w342} />}
                                    </div>
                                    <div className="details">
                                        <h5 className="title">{getName(movie)}</h5>
                                        <span className="playtime">{movie.tmdb?.release_date}</span>
                                        <div className="rating">{movie.tmdb?.vote_average}</div>
                                        <a className="icon playicon" onClick={e => movie_click(movie)}>
                                            <img src="../img/media/play-icon.svg" />
                                        </a>
                                        <button className="status">View</button>
                                        <button className="status" onClick={e => markAsWatched(movie)}>
                                            mark as watched
                                        </button>
                                    </div>
                                </li>
                            ))}
                        </ul>
                    </div>
                </div>
            )}
            <div style={{ color: "white" }}>
                {app.config && (
                    <div>
                        <h3>Folders</h3>
                        {app.config.folders?.map(folder => (
                            <div>
                                <input value={folder.path} />
                            </div>
                        ))}
                        <button onClick={e => addConfigFolder()}>+</button>
                        <button onClick={e => app.saveConfig()}>save</button>
                        <button onClick={e => scan()}>scan</button>
                        <button onClick={e => reAnalyze()}>re-analyze</button>
                        <label>
                            {skip}-{skip + pageSize} / {filteredMovies?.length} (total: {allMovies?.length})
                        </label>
                        <button onClick={e => prevPage()}>Prev Page</button>
                        <button onClick={e => nextPage()}>Next Page</button>
                        <button onClick={e => app.tmdbApp.tmdb.loginToTmdb()}>tmdb login</button>
                        <button onClick={e => tmdbV4Login()}>tmdb v4 login</button>
                        <button onClick={e => tmdbV4Tests()}>tmdb v4 tests</button>
                        <button onClick={e => getAllMediaFiles()}>Refresh</button>
                        <button onClick={e => app.tmdbApp.tmdb.markAllRatedAsWatched()}>
                            Mark all rated as watched
                        </button>
                        <button onClick={e => app.tmdbApp.downloadRatings()}>Download Ratings</button>
                        <button onClick={e => app.tmdbApp.downloadWatchlists()}>downloadWatchlists</button>
                        <button onClick={e => app.tmdbApp.getSavedRatings()}>getSavedRatings</button>
                        <button onClick={e => tvAiringToday()}>airing today</button>
                        <button onClick={e => tvOnTheAir()}>on the air</button>
                    </div>
                )}
                <div>
                    <pre>{JSON.stringify(scanStatus)}</pre>
                </div>
                <div>
                    {movies?.map(media => (
                        <div>
                            <span>{getName(media)}</span> - <span>{media.fsEntry?.mtime}</span>
                            <button onClick={e => markAsWatched(media)}>mark as watched</button>
                            <label>watched={media.md?.watched}</label>
                            <button className={cx(canPlay(media) && "disabled")} onClick={e => play(media)}>
                                Play
                            </button>
                        </div>
                    ))}
                </div>
                <br />
                <br />
                <br />
                <br />
                <br />
                <br />
                <br />
                <br />
                <br />
                <br />
                <br />
                <br />
                <br />
            </div>
        </>
    )
}

// client/src/media.component.ts
import { Component, OnInit, OnChanges, SimpleChanges } from '@angular/core';
import { TmdbClient } from "./tmdb-client"
import { TmdbMovie, TmdbMedia, TmdbMovieDetails, TmdbTvShowDetails } from "./tmdb/tmdb-api"
import { FileService, } from "./service"
import { promiseEach, promiseMap, arrayDistinctBy } from "./utils/utils"
import { App, Config, MediaFile } from "./app"
import { Media, Movie, TvShow } from "./media"
import { File } from "contracts"

@Component({
    selector: 'my-media',
    templateUrl: '/src/media.component.html',
    styleUrls: ['_res_/src/media.component.css'],
})
export class MediaComponent implements OnInit, OnChanges {
    constructor(private app: App) {

    }

    movies: MediaFile[];
    filteredMovies: MediaFile[];
    selectedMovie: MediaFile;

    ngOnInit(): void {
        this.app.init()
            .then(() => this.getAvailableMedia())
            .then(() => this.getPopularMovies())
            ;
        //this.test4();
        //this.app.tmdbV4.invoke(t=>t.accountGetCreatedLists({}));
    }
    ngOnChanges(changes: SimpleChanges): void { }

    filterType: "movie" | "tv" | null;

    applyFilter() {
        let list = this.movies;
        list = this.applyFilterType(list);
        this.filteredMovies = list;
    }

    applyFilterType(list: MediaFile[]): MediaFile[] {
        if (this.filterType == null)
            return list;
        return list.filter(t => t.type == this.filterType);
    }

    movie_click(movie: MediaFile) {
        this.selectedMovie = movie;
    }

    goBack() {
        this.selectedMovie = null;
    }

    async getPopularMovies() {
        if (this.movies != null && this.movies.length > 0)
            return;
        let e = await this.app.tmdb.movieGetPopular({ language: "en" });
        this.movies = e.results.map(t => <MediaFile>{ md: {}, tmdb: t });
        console.log(this.movies);
    }
    async getAvailableMedia() {
        let list = await this.app.getAvailableMedia();
        let list2 = list.orderBy(t => [t.md.tmdbKey ? "1" : "2", t.md.watched ? "1" : "2", t.type, t.md.key].join("\t"));
        console.log(list2);
        this.movies = list2.take(20);
        await this.app.loadTmdbMediaDetails(this.movies);
    }

    getName(mf: MediaFile): string {
        let name = mf.md.key;
        if (mf.tmdb != null)
            name = mf.tmdb.name || mf.tmdb.title;
        else if (mf.parsed != null)
            name = mf.parsed.name;
        if (mf.md.episodeKey != null)
            name += " " + mf.md.episodeKey
        return name;
    }

    async play(mf: MediaFile): Promise<any> {
        if (mf == null || mf.md == null)
            return;
        let file: File = null;
        if (mf.md.lastKnownPath != null)
            file = await this.app.fileService.GetFile({ Path: mf.md.lastKnownPath });
        if (file == null)
            file = await this.app.findFile(mf.md.key);
        if (file == null)
            return;
        await this.app.fileService.Execute({ Path: file.Path });
    }

    tmdbV4Login() {
        this.app.tmdbV4.loginToTmdb().then(e => console.log("LOGIN COMPLETE"));
    }

    markAsWatched(mf: MediaFile) {
        return this.app.markAsWatched(mf);
        //return this.app.tmdb.markAsWatched(media.id);
    }

    addConfigFolder() {
        this.app.config.folders.push({ path: null });
    }

    async tvAiringToday() {
        let favs = await this.app.tmdb.proxy.getAllPages(t => t.accountGetFavoriteTVShows({}));
        console.log("favs", favs.map(t => t.name));
        let airingToday = await this.app.tmdb.proxy.getAllPages(t => t.tvGetTVAiringToday({})); //timezone: "Europe/Amsterdam"
        console.log("airingToday", airingToday.map(t => t.name));
        console.log(airingToday.map(t => t.name), airingToday);
        let favIds = new Set(favs.map(t => t.id));
        let favAiringToday = airingToday.filter(t => favIds.has(t.id));
        console.log("favAiringToday", favAiringToday.map(t => t.name));
        let x = await this.app.tmdb.tvGetDetails({ tv_id: favAiringToday[0].id });
        let x2 = await this.app.tmdb.tvGetSeason({ tv_id: favAiringToday[0].id, season_number:x.seasons.last().season_number });
        console.log("TV DETAILS", x, x2);

    }
    async tvOnTheAir() {
        let onTheAir = await this.app.tmdb.proxy.getAllPages(t => t.tvGetTVOnTheAir({}));
        console.log(onTheAir.map(t => t.name), onTheAir);
    }


}


<div *ngIf="selectedMovie != null">
    <div class="selectedMovie" [ngStyle]="{ 'background': 'transparent url(' + selectedMovie.tmdb?.backdrop?.original + ') top center no-repeat', 'background-size': 'cover' }">
        <div class="background-cover">
            <button class="backBtn" (click)="goBack()">Back</button>
            <div class="cover"><img src="{{selectedMovie.tmdb?.poster?.w342}}" /></div>
            <div class="detailsLarge">
                <h3 class="title">{{getName(selectedMovie)}}</h3>
                <div class="tag">{{selectedMovie.tmdb?.tagline}}</div>
                <div class="metadata">
                    <span class="rate">
                        <object type="image/svg+xml" data="../img/media/rate-icon.svg"></object>{{selectedMovie.tmdb?.vote_average}}
                    </span>
                    <span>{{selectedMovie.tmdb?.release_date}}</span>
                    <span>{{selectedMovie.tmdb?.runtime}} minutes</span>
                    <span>{{selectedMovie.tmdb?.genres?.name}}</span>
                </div>
                <p class="synopsis">{{selectedMovie.tmdb?.overview}}</p>
            </div>
        </div>
    </div>
</div>
<div class="media" *ngIf="selectedMovie == null">
    <div class="leftpane">
        <header class="header">
            <a class="logo">
                <img src="../img/media/logo.svg" />
            </a>
        </header>
        <div class="filter local" (click)="onFiltersChanged()">
            <span class="title">Watchlist</span>
            <button [class.selected]="filter.type == null" (click)="filter.type = null" class="allmedia">All Media</button>
            <button [class.selected]="filter.type == 'tv'" (click)="filter.type = 'tv'" class="tv">TV Shows</button>
            <button [class.selected]="filter.type == 'movie'" (click)="filter.type = 'movie'" class="movie">Movies</button>
            <hr />
            <button [class.selected]="filter.watched == null" (click)="filter.watched = null" class="selected">Both</button>
            <button [class.selected]="filter.watched == true" (click)="filter.watched = true">Watched</button>
            <button [class.selected]="filter.watched == false" (click)="filter.watched = false">Not Watched</button>
            <hr />
            <button [class.selected]="filter.groupSimilar == true" (click)="filter.groupSimilar  = true">Group</button>
            <button [class.selected]="filter.groupSimilar == false" (click)="filter.groupSimilar = false">Ungroup</button>
            <hr />
            <button [class.selected]="filter.sortBy == 'fsEntry.mtime desc'" (click)="filter.sortBy = 'fsEntry.mtime desc'">Sort1</button>
            <button [class.selected]="filter.sortBy == 'fsEntry.mtime asc'" (click)="filter.sortBy = 'fsEntry.mtime asc'">Sort2</button>
            <button [class.selected]="filter.sortBy == 'md.episodeKey desc'" (click)="filter.sortBy = 'md.episodeKey desc'">Sort3</button>
            <button [class.selected]="filter.sortBy == 'md.episodeKey asc'" (click)="filter.sortBy = 'md.episodeKey asc'">Sort4</button>
        </div>
        <div class="filter explore">
            <span class="title">Explore</span>
            <button class="allmedia">Most Popular</button>
            <button class="tv">Your Feed</button>
            <button class="movie">Recommended</button>
        </div>
    </div>
    <!-- Leftpane ends here -->
    <div class="rightpane">
        <div class="gridtop">
            <!-- <div class="title">your watchlist</div> -->
            <div class="search">
                <input type="text" placeholder="Quick Search" [(ngModel)]="filter.search" (input)="scheduleApplyFilter()" />
            </div>
        </div>
        <!-- <h3 class="title">your watchlist</h3> -->
        <ul class="pool">
            <li *ngFor="let movie of movies" class="media" [class.has-poster]="movie.tmdb?.poster?.w342 != null">
                <div class="poster">
                    <img *ngIf="movie.tmdb?.poster?.w342" src="{{movie.tmdb?.poster?.w342}}">
                </div>
                <div class="details">
                    <h5 class="title">{{getName(movie)}}</h5>
                    <span class="playtime">{{movie.tmdb?.release_date}}</span>
                    <div class="rating">{{movie.tmdb?.vote_average}}</div>
                    <a class="icon playicon" (click)="movie_click(movie)"><img src="../img/media/play-icon.svg" /></a>
                    <button class="status">View</button>
                    <button class="status" (click)="markAsWatched(movie)">mark as watched</button>
                </div>
            </li>
        </ul>
    </div><!-- End of Right pane -->
</div>
<div style="color:white">
    <div *ngIf="app.config!=null">
        <h3>Folders</h3>
        <div *ngFor="let folder of app.config.folders">
            <input [(ngModel)]="folder.path" />
        </div>
        <button (click)="addConfigFolder()">+</button>
        <button (click)="app.saveConfig()">save</button>
        <button (click)="scan()">scan</button>
        <button (click)="reAnalyze()">re-analyze</button>
        <label>{{skip}}-{{skip+pageSize}} / {{filteredMovies?.length}} (total: {{allMovies?.length}})</label>
        <button (click)="prevPage()">Prev Page</button>
        <button (click)="nextPage()">Next Page</button>
        <button (click)="app.tmdb.loginToTmdb()">tmdb login</button>
        <button (click)="tmdbV4Login()">tmdb v4 login</button>
        <button (click)="tmdbV4Tests()">tmdb v4 tests</button>
        <button (click)="getAllMediaFiles()">Refresh</button>
        <button (click)="app.tmdb.markAllRatedAsWatched()">Mark all rated as watched</button>
        <button (click)="app.downloadRatings()">Download Ratings</button>
        <button (click)="app.downloadWatchlists()">downloadWatchlists</button>
        <button (click)="app.getSavedRatings()">getSavedRatings</button>
        <button (click)="tvAiringToday()">airing today</button>
        <button (click)="tvOnTheAir()">on the air</button>
    </div>
    <div>
        <pre>{{scanStatus | json}}</pre>
    </div>
    <div>
        <div *ngFor="let media of movies">
            <span>{{getName(media)}}</span> - <span>{{media.fsEntry?.mtime}}</span>
            <button (click)="markAsWatched(media)">mark as watched</button>
            <label>watched={{media.md?.watched}}</label>
            <button [class.disabled]="canPlay(media)" (click)="play(media)">Play</button>
        </div>
    </div>
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />
</div>
